### ISSUE TITLE
questions regarding coal modeling

### ISSUE THREAD

**Issue by hongxuchen** [siis/ic3#14]
It's a coal specific _question_ (not _issue_) however tightly relevant to android icc APIs.

As to [Intent.model](https://github.com/siis/ic3/blob/dd135e95230e52902f9f9df99606915fd81ea1ee/src/main/resources/model/Intent.model) of https://github.com/siis/ic3/commit/20e3164ddebfdac08609df5125da3388e00316f5 , some query declarations are `Activity` specific, but it is modeled as a more general parent class `Context`, so is it deliberately designed so?

Another question is that some "exit" methods of `Activity` is ignored, e.g., `startIntentSenderFromChild`. From android document this api is added from Level 16. In my viewpoint, it should also be intent relevant since it passes an intent and may start another activity similarly.

**Comment by docteau** [comment]
Hi,

You are correct that some of the method are specific to Activity and not Context. However, since Activity is a subclass of Context this should not be a problem. To be thorough it could be fixed for future versions of IC3.

In general I agree that it would be nice to support methods from new API versions.

**Comment by hongxuchen** [comment]
@docteau Got it and thanks for the clarification!
