### ISSUE TITLE
Build of IC3 failed

### ISSUE THREAD

**Issue by vitaliiavdiienko** [siis/ic3#3]
Hi,

i have followed instructions from http://siis.cse.psu.edu/ic3/source.html in order to build IC3, but I got a following exception while building:
`[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.739s
[INFO] Finished at: Mon Jun 15 16:39:45 CEST 2015
[INFO] Final Memory: 6M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ic3: Could not resolve dependencies for project edu.psu.cse.siis:ic3:jar:0.1.1-SNAPSHOT: Could not find artifact edu.psu.cse.siis:coal:jar:0.1.7-SNAPSHOT in soot-repo (https://raw.github.com/siis/soot/mvn-repo/) -> [Help 1]
`

Can you help me with this?

Thank you in advance,
Vitalii

**Comment by docteau** [comment]
Hi,

The current version of the IC3 code is meant to work with a development version of COAL. You can checkout the latest tag (currently v0.1.0) of IC3 using git before building (git checkout v0.1.0).

Alternatively, at any other time you could checkout projects coal-strings and coal from our repository and run mvn install on them before trying to build IC3, but I am in the middle of a big update and versions are not currently compatible. That should be fixed in the next couple of days when I push an update of IC3 compatible with the latest COAL, in case you want to check the latest revision.

**Comment by docteau** [comment]
Hi,

I have moved the latest commits to a new "develop" branch. You should now be able to just follow the instructions from the IC3 webpage to build the source code.

**Comment by vitaliiavdiienko** [comment]
Hi Damien,

thanks a lot!

Now everything works fine.

Best Regards,
Vitalii
