### ISSUE TITLE
A huge scalability problems of IC3

### ISSUE THREAD

**Issue by vitaliiavdiienko** [siis/ic3#5]
Hi Damien,

i am trying to run IC3 on real-world apps from Google Play Store, but unfortunately the analysis for most of them never finishes. I have 2 days per app as a timeout but no success at all.

Do you have any idea how to improve the runtime of IC3? Maybe I can use some parameters?

Thanks in advance.

Best Regards,
Vitalii

**Comment by docteau** [comment]
Hi Vitalii,

It definitely shouldn't be the case that the analysis for most of them doesn't finish. Have you checked the available memory on your system? In my experience this type of thing could occur if you run out of RAM and your system starts swapping to the hard drive. If this is indeed the root of your problem, you should make sure that you set the heap size appropriately and that you don't run too many instances in parallel on the same system.

In order to improve performance further, you can compile the latest snapshot version of IC3 on the develop branch. It uses a more recent and faster version of Soot. If you do so, you should make sure that you also compile the latest version of the COAL (develop branch) and COAL-strings projects.

Best,
Damien

**Comment by vitaliiavdiienko** [comment]
Hi Damien,
i have tried to compile a development branch of IC3 with precompiled COAL-dev. It seems that IC3-dev relies on some classes which are not exist in COAL-dev.

for example:
`edu.psu.cse.siis.coal.arguments.LanguageConstraints.Call`

does not exist in COAL-dev.

Thanks

**Comment by docteau** [comment]
Hi Vitalii,

You need to run the following before compiling COAL:

    mvn clone https://github.com/siis/coal-strings.git
    cd coal-strings
    mvn install

Best,
Damien
