### ISSUE TITLE
IC3 is unable to find startActivity call

### ISSUE THREAD

**Issue by vitaliiavdiienko** [siis/ic3#7]
Hi Damien,

i have developed a simple app, which reads IMEI in one activity, then passes it to another activity and then sends it via SMS.

But it seems that IC3 can not identify startActivity of the first component.
Can you take a look on it?
An Apk can be found here: https://drive.google.com/file/d/0BxV2Pl6rGO7uaGs1RDBBLUZNNUU/view?usp=sharing

Thank you in advance.

Best Regards,
Vitalii

**Comment by docteau** [comment]
Hi Vitalii,

It looks like method goToTheSecond(), which contains the call you are referring to, is not itself reachable. You should make sure that it is called by an entry point (e.g., by onCreate()). Otherwise, IC3 is correct in not identifying this call as it cannot be executed at runtime.

Best,
Damien
